DefaultContentLanguage: "en"
copyright: "Copyright 2011-2016 Endre Szabo"
description: "yet another tech blog with underdeveloped thoughts, quick and dirty tips and tricks, random ramblings"
baseURL: https://www.qssl.org/~eszabo/
languageCode: en-us
title: Endre Szabo
MetaDataFormat: yaml
theme: hugo-theme-end.re
pygmentsUseClasses: true
pygmentsStyle: vim
pygmentsCodeFences: true
preserveTaxonomyNames: false
RemovePathAccents: false
pluralizelisttitles: false
#defaultContentLanguageInSubdir: true
enableGitInfo: true
uglyURLs: true
newContentEditor: /usr/bin/vim
blackfriday:
    hrefTargetBlank: true
permalinks:
    default: /:slug
    blog: /blog/:slug
params:
    disqusShortname: endreszabo
    Subtitle: "Endre shares his thoughts with you"
    Description: "yet another tech blog with underdeveloped thoughts, quick and dirty tips and tricks, random ramblings"
    AuthorName: "Endre Szabo"
    Author: "Endre Szabo"
    monthNames:
        1: Jan
        2: Feb
        3: Mar
        4: Apr
        5: May
        6: Jun
        7: Jul
        8: Aug
        9: Sep
        10: Oct
        11: Nov
        12: Dec
Author: "Endre Szabo"
menu:
    main:
      - url: '/index.html'
        name: 'About'
        weight: 0
      - url: '/blog.html'
        name: 'Blog'
        weight: 2
      - url: '/tutorial.html'
        name: 'Tutorials'
        weight: 3
      - url: '/hu/'
        name: '[Ugyanez magyarul]'
        weight: 1
axonomies:
    tags: "tags"
    categories: "categories"
Languages:
    en:
        weight: 1
    hu:
        taxonomies:
            tags: "címkék"
            categories: "kategóriák"
        params:
            subtitle: Endre megosztja a gondolatait veled
            monthNames:
                1: Jan
                2: Feb
                3: Már
                4: Ápr
                5: Máj
                6: Jún
                7: Júl
axonomies:
    tags: "tags"
    categories: "categories"
Languages:
    en:
        weight: 1
    hu:
        taxonomies:
            tags: "címkék"
            categories: "kategóriák"
        params:
            subtitle: Endre megosztja a gondolatait veled
            monthNames:
                1: Jan
                2: Feb
                3: Már
                4: Ápr
                5: Máj
                6: Jún
                7: Júl
                8: Aug
                9: Szept
                10: Okt
                11: Nov
                12: Dec
        weight: 2
        navigation:
            about: Rólam
        Author: "Szabó Endre"
        menu:
            main:
              - url: '/hu/index.html'
                name: 'Rólam'
                weight: 0
              - url: '/hu/blog.html'
                name: 'Blog'
                weight: 2
              - url: '/hu/tutorialok.html'
                name: 'Tutorialok'
                weight: 3
              - url: '/'
                name: '[Same in English]'
                weight: 1
##outputFormats:
outputFormats:
    RSS:
        mediatype: "application/rss"
        baseName: "feed/index"
